FROM node:10
EXPOSE 2020

WORKDIR /src

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.babelrc .
COPY ./.env.production .
COPY ./.env.development .
COPY ./tsconfig.json .
COPY ./wait-for-it.sh .
COPY ./api/ ./api/

RUN yarn install

WORKDIR ./api
