version: "3"
services:
  ui-prod:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - 80:80
    volumes:
      - ./:/ui
    depends_on:
      - api-prod

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 2020:80
    volumes:
      - ./:/api

  ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - 80:80
    volumes:
      - ./:/ui
    depends_on:
      - api-dev
    command: bash -c 'yarn --cwd ui run development'

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 2020:80
    volumes:
      - ./:/api
    command: bash -c 'yarn --cwd api run development'
