FROM node:10-alpine
EXPOSE 2020
EXPOSE 80
CMD ["yarn", "start:production"]

WORKDIR /src

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.babelrc .
COPY ./.env.production .
COPY ./.env.development .
COPY ./tsconfig.json .
COPY ./api/ ./api/

RUN yarn install

WORKDIR ./api
