FROM node:10-alpine

WORKDIR /src

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.babelrc .
COPY ./.env.production .
COPY ./.env.development .
COPY ./tsconfig.json .
COPY ./api/ ./api/

RUN yarn install

EXPOSE 2020

CMD ["yarn", "--cwd", "api", "start:production"]
