service: internote-health-service

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    config: "webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "yarn"
  domains:
    prod: services.internote.app
    dev: dev-services.internote.app
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: "internote.app"
    stage: "${self:custom.stage}"
    createRoute53Record: true
    endpointType: "regional"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 256
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-domain-manager

functions:
  health:
    handler: health.handler
    events:
      - http:
          path: health
          method: get
          cors: true
  authenticated:
    handler: authenticated.handler
    events:
      - http:
          path: authenticated
          method: get
          cors: true
          authorizer: aws_iam

resources:
  # As this is the main service, API gateway is exposed here
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiId
    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiRootResourceId
