export interface Theme {
  appBackground: string;
  appText: string;
  headingBackground: string;
  modalBackdropBackground: string;
  dropdownMenuItemText: string;
  primaryButtonText: string;
  secondaryButtonText: string;
  inputBackground: string;
  secondaryButtonBackground: string;
  primaryButtonBackground: string;
  savingActive: string;
  savingInactive: string;
  textLinkText: string;
  codeBlockBackground: string;
  formatButtonActiveBackground: string;
  formatButtonActiveText: string;
  formatButtonInactiveText: string;
  formatButtonInactiveBackground: string;
  blockQuoteBorder: string;
  toolbarBackground: string;
  dropdownMenuBackground: string;
  inputLabelText: string;
  modalCloseIconColor: string;
  searchInputBackground: string;
  searchInputFocusedBackground: string;
  searchInputText: string;
  notesMenuItemTextInactive: string;
}

export const ocean: Theme = {
  appBackground: "#0f0d16",
  appText: "#D0D2D4",
  headingBackground: "#0f0d16",
  modalBackdropBackground: "#0f0d16",
  dropdownMenuItemText: "#D0D2D4",
  primaryButtonText: "#FFFFFF",
  secondaryButtonText: "#D0D2D4",
  inputBackground: "#19181B",
  secondaryButtonBackground: "#19181B",
  primaryButtonBackground: "#095efd",
  savingActive: "#095efd",
  savingInactive: "#2CCB62",
  textLinkText: "#D0D2D4",
  codeBlockBackground: "#211F28",
  formatButtonActiveBackground: "#095efd",
  formatButtonActiveText: "#FFFFFF",
  formatButtonInactiveBackground: "#19181B",
  formatButtonInactiveText: "#504D5D",
  blockQuoteBorder: "#504D5D",
  toolbarBackground: "#000000",
  dropdownMenuBackground: "#000000",
  inputLabelText: "#737278",
  modalCloseIconColor: "#737278",
  searchInputBackground: "#000000",
  searchInputFocusedBackground: "#19181B",
  searchInputText: "#FFFFFF",
  notesMenuItemTextInactive: "#999999"
};
