service: internote-dictionary-service

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
  webpack:
    config: "webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "yarn"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    REGION: eu-west-1
    OXFORD_API_ID: ${ssm:/internote/${self:custom.stage}/OXFORD_API_ID}
    OXFORD_API_KEY: ${ssm:/internote/${self:custom.stage}/OXFORD_API_KEY}
  memorySize: 256
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ApiGatewayRestApiRootResourceId

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack

functions:
  lookup:
    handler: lookup.handler
    events:
      - http:
          path: dictionary/lookup
          method: post
          cors: true
          authorizer: aws_iam
