service: internote-ui

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-include-dependencies
  - serverless-domain-manager
  - serverless-nextjs-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: internote.app
    dev: dev.internote.app
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: "internote.app"
    stage: "${self:custom.stage}"
    createRoute53Record: true
    endpointType: "regional"
  serverless-nextjs:
    createAssetBucket: true # TODO: PR to https://github.com/danielcondemarin/serverless-nextjs-plugin to check for existence of bucket before creating it
    cloudFront:
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.domains.${self:custom.stage}}
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:eu-west-1:822567739604:certificate/36c91c47-2303-4f85-b4b4-f4742b55748d

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 256
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    STAGE: ${self:custom.stage}
# resources:
#   Resources:
# InternoteUiStaticBucket:
#   Type: AWS::S3::Bucket
#   Properties:
#     BucketName: "internote-${self:custom.stage}-ui-static"
#     AccessControl: PublicRead
# InternoteUiStaticBucketPolicy:
#   Type: AWS::S3::BucketPolicy
#   Properties:
#     Bucket:
#       Ref: InternoteUiStaticBucket
#     PolicyDocument:
#       Statement:
#         - Sid: PublicReadGetObject
#           Effect: Allow
#           Principal: "*"
#           Action:
#             - s3:GetObject
#           Resource: arn:aws:s3:::internote-${self:custom.stage}-ui-static/*

package:
  exclude:
    - ./**
