service: internote-ui

functions:
  authenticate:
    handler: generated-lambdas/authenticate.handler
    events:
      - http:
          method: GET
          path: /authenticate/
          cors: true
      - http:
          method: ANY
          path: /authenticate/{any+}
          cors: true
  index:
    handler: generated-lambdas/index.handler
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: ANY
          path: /{any+}
          cors: true

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-offline
  - serverless-s3-sync
  - serverless-domain-manager

custom:
  s3Sync:
    - bucketName: internote-${self:custom.stage}-ui-static
      localDir: .static
  serverless-offline:
    port: 3000
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: internote.app
    dev: dev.internote.app
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: "internote.app"
    stage: "${self:custom.stage}"
    createRoute53Record: true
    endpointType: "regional"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 256
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024

resources:
  Resources:
    InternoteUiStaticBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "internote-${self:custom.stage}-ui-static"
        AccessControl: PublicRead
    InternoteUiStaticBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: InternoteUiStaticBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::internote-${self:custom.stage}-ui-static/*
