service: internote-ui

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules:
      forceInclude:
        - "@fortawesome/fontawesome-svg-core"
        - "@fortawesome/free-solid-svg-icons"
        - "@fortawesome/react-fontawesome"
        - "@internote/api"
        - "@rebass/grid"
        - "aws-sdk"
        - "aws-serverless-express"
        - "cookie"
        - "express"
        - "express-http-proxy"
        - "is-hotkey"
        - "lodash"
        - "next"
        - "react"
        - "react-dom"
        - "slate"
        - "slate-html-serializer"
        - "slate-react"
        - "styled-components"
        - "twine-js"
        - "universal-cookie"
    packager: "yarn"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128

functions:
  server:
    handler: lambda.handler
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: GET
          path: /static/{any+}
          cors: true
      - http:
          method: GET
          path: /_next/{proxy+} # Catch Next specific routes
          cors: true
      - http:
          method: ANY
          path: /{any+} # Catch all unknown routes and redirect to main handler
          cors: true
