service: internote-ui

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-include-dependencies
  - serverless-domain-manager
  - serverless-nextjs-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: internote.app
    dev: dev.internote.app
  assetsBucketNames:
    prod: internote-prod-ui-static
    dev: internote-dev-ui-static
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: "internote.app"
    stage: "${self:custom.stage}"
    createRoute53Record: true
    endpointType: "regional"
  serverless-nextjs:
    createAssetBucket: true
    assetsBucketName: ${self:custom.assetsBucketNames.${self:custom.stage}}
    cloudFront:
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.domains.${self:custom.stage}}
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:822567739604:certificate/cba4ce61-ca15-4d6b-8eac-3569e4eae88b
            SslSupportMethod: sni-only

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 256
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    STAGE: ${self:custom.stage}
# resources:
#   Resources:
# InternoteUiStaticBucket:
#   Type: AWS::S3::Bucket
#   Properties:
#     BucketName: "internote-${self:custom.stage}-ui-static"
#     AccessControl: PublicRead
# InternoteUiStaticBucketPolicy:
#   Type: AWS::S3::BucketPolicy
#   Properties:
#     Bucket:
#       Ref: InternoteUiStaticBucket
#     PolicyDocument:
#       Statement:
#         - Sid: PublicReadGetObject
#           Effect: Allow
#           Principal: "*"
#           Action:
#             - s3:GetObject
#           Resource: arn:aws:s3:::internote-${self:custom.stage}-ui-static/*

package:
  exclude:
    - ./**
