service: internote-ui

functions:
  login:
    handler: .lambdas/login.handler
    events:
      - http:
          method: GET
          path: /login/
          cors: true
      - http:
          method: ANY
          path: /login/{any+}
          cors: true
  # register:
  #   handler: .lambdas/register.handler
  #   events:
  #     - http:
  #         method: GET
  #         path: /register/
  #         cors: true
  #     - http:
  #         method: ANY
  #         path: /register/{any+}
  #         cors: true
  # index:
  #   handler: .lambdas/index.handler
  #   events:
  #     - http:
  #         method: GET
  #         path: /
  #         cors: true
  #     - http:
  #         method: ANY
  #         path: /{any+}
  #         cors: true

plugins:
  - serverless-offline
  - serverless-s3-sync

custom:
  serverless-offline:
    port: 3000
  s3Sync:
    - bucketName: internote-ui-static
    - localDir: .next/static
    - acl: public-read

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128
# resources:
#   Resources:
#     NextStaticBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: internote-ui-static
