service: internote-ui

plugins:
  - serverless-plugin-typescript
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: "../webpack.config.js"
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128

functions:
  server:
    handler: lambda.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /static/{any+}
      - http:
          method: GET
          path: /_next/{proxy+} # Catch Next specific routes
      - http:
          method: ANY
          path: /{any+} # Catch all unknown routes and redirect to main handler
