name: internote-ui

app:
  component: serverless-next.js
  inputs:
    domain: ["dev", "internote.app"]
    bucketName: internote-ui
    build:
      env:
        NODE_ENV: production
# storybook:
#   component: "@serverless/website"
#   inputs:
#     code:
#       src: storybook-static
#     domain: storybook.internote.app
#     region: eu-west-1
#     bucketName: internote-storybook
