service: internote-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  serverless-offline:
    port: 2020
  customDomain:
    domainName: api.internote.app
    certificateName: "internote.app"
    createRoute53Record: true
    endpointType: "regional"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: SpeechBucket
            - "/*"
    - Effect: "Allow"
      Action:
        - "polly:*"
      Resource: "*"

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      SPEECH_BUCKET:
        Ref: SpeechBucket
      REGION: ${self:provider.region}

resources:
  Resources:
    SpeechBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: internote-api-speech
        AccessControl: PublicRead
