service: internote-api

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.internote.app
    dev: dev-api.internote.app
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: "internote.app"
    stage: "${self:custom.stage}"
    createRoute53Record: true
    endpointType: "regional"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 1024
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
  throttle:
    burstLimit: 5 # Limit connections to the database
    rateLimit: 5 # Limit connections to the database
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: SpeechBucket
            - "/*"
    - Effect: "Allow"
      Action:
        - "polly:*"
      Resource: "*"

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      SPEECH_BUCKET:
        Ref: SpeechBucket
      REGION: ${self:provider.region}

resources:
  Resources:
    SpeechBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "internote-${self:custom.stage}-api-speech"
        AccessControl: PublicRead
